#!/bin/bash

#:
function ^build() { #:🔨:builds a package for pypi
  virtualenv .2 -p 2 && .2/bin/python setup.py sdist bdist_wheel
  virtualenv .3 -p 3 && .3/bin/python setup.py sdist bdist_wheel
  rm -rf .2 .3
}

function ^clean() { #:🧹:removing the .venv and cleaning cache
  rm -rf .pytest_cache .venv build dist '*.egg-info'
  find . -type d -name '__pycache__' -exec rm -rf {} \;
  find . -type f -name '*.pyc' -exec rm {} \;
}

#:
function ^help() { #:🆘:display this
  grep -v _no_grep_ "$_0" | grep '#:' | awk -F '#:' '{split($1, _func, " "); split(_func[2], _func, "("); split($2, _desc, ":"); printf "  %s %-12s%s\n", _desc[1], substr(_func[1], 2), _desc[2]}'
}

cd "$(dirname "$0")" && _0="./$(basename "$0")" && ([ "$1" = '-' ] && (grep -v _no_grep_ "$_0" | grep '^.*()' | awk -F ^ '{split($2, _func, "("); print _func[1]}')) || ([ -z "$1" ] || ! "$_0" - | grep -qw "$1" && ^help) || "^$@"
